remote_theme: pmarsceill/just-the-docs
title: AWS Tutorial
search_enabled: true
aux_links:
        "Nadeau Lab on GitHub":
                - "https://github.com/nadeaulab/"
custom_ami: ami-0ad52717c4558ea80
